server:
  port: 8000

spring:
  application:
    name: CONFIG-SERVICE

  cloud:
    config:
      server:
        git:
          uri: https://github.com/poornimaVarshney0852/SpringCloudConfigurationProperties

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/

logging:
  level:
    root: DEBUG
    org.springframework.cloud: DEBUG
    com.yourpackage: DEBUG
    com.yourpackage.YourClass: TRACE


#okta configuration for api gateway

#okta:
#  oauth2:
#    issuer: https://dev-77584981.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oa7w65a24Px9Oyms5d7
#    client-secret: JfsTTqODW21uapbbhKjW42sGzjcNs86GN7WL5dfU
#    scopes: openid, profile, email, offline_access
